[project]

name = "tsp-genetic"
description = "tsp_genetic"

version = "0.1.0"
readme = "README.md"

requires-python = ">= 3.13"
dependencies = [
    "geopandas>=1.1.1",
    "geopy>=2.4.1",
    "mlflow>=3.3.2",
    "typer>=0.17.3",
]

[project.scripts]
tsp-genetic = "tsp_genetic"
